fixtures:
  forge_modules:
    apt:
      repo: "puppetlabs/apt"
      ref: "1.6.0"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.3.2"
  repositories:
  symlinks:
    transmission: "#{source_dir}"