rvm: 
  - 1.8.7
  - 1.9.3
  - ruby-head
before_install:
  - gem update --system
  - gem --version
notifications:
  hipchat:
    rooms:
      secure: MngXz9HMjctxOotbS9j61+yH4FvDRW5GNxU9PiAI3JNMeqS9ypj/RrhLJJCB+Enx+6c6cEV9ecW0UHMuukq9OgphhCHgrYIgOqDAt/P7fRg8PFTKLl9IZcpKYIlinRHFtZM+hehYMQFXdfPZfknneLLWI6SEZ9PvajreQw26gz8=
env:
- PUPPET_VERSION="~> 3.7.0"
- PUPPET_VERSION="~> 3.6.0"
- PUPPET_VERSION="~> 3.5.0"
- PUPPET_VERSION="~> 3.0.0"
- PUPPET_VERSION="~> 2.7.0"
